name: CI

on:
  workflow_call: {}
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x, 24.x, 26.x ]

    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Test
        run: |
          npm test
      - name: Test Dist
        run: |
          rm -rf node_modules
          npm ci --omit=dev
          npm run test:dist
